apiVersion: v1
kind: Pod
metadata:
  name: dummy-project
  labels:
    app: dummy-project
spec :

  containers:
    - name: redis-container
      image: redis:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379

    - name : frontend-container
      image : frontend_service_image:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6000
          hostPort: 6000
    
    - name : productservice-container
      image : vinod_productservice:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6200
          hostPort: 6200

    - name : orderservice-container
      image : vinod_orderservice:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6100
          hostPort: 6100

    - name : userservice-container
      image : userservice_image:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6300
          hostPort: 6300

    
