apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: dummy-project
  ports:
  - name: frontend
    port: 5000
    targetPort: 6000

  - name: product
    port: 5200
    targetPort: 6200

  - name: user
    port: 5300
    targetPort: 6300

  - name: order
    port: 5100
    targetPort: 6100
    
  type: NodePort