apiVersion: v1
kind: Pod
metadata:
  name: data-tier
  labels:
    app: dummy-project
    tier: data
spec:
  containers:
    - name: redis-container
      image : redis:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: data-tier
  labels:
    app: dummy-project
spec:
  ports:
  - name: redis 
    port: 8200
    targetPort: 6379 #container-port

  selector:
    tier: data
  type: NodePort



     